apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
spec:
  issuerRef:
    name: letsencrypt-production-dns01
    kind: ClusterIssuer
  secretName: keycloak-certificate
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
    - "keycloak.apps.obs.nerc.mghpcc.org"
