apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prom-keycloak-proxy-certs
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: prom-keycloak-proxy-certs
  dataFrom:
  - extract:
      key: nerc/nerc-ocp-obs/prom-keycloak-proxy/certs
